export default {
  id: "library_duel",
  order: 30,
  legacy: true,
  hidden: true,
  mapId: "library",
  sceneName: "图书馆决斗",
  emoji: "⚔️",
  cardDesc: "在出拳人群中击败对手",
  mission: "图书馆里挤满了出拳的读者，击败你的对手！",
  hudMission: "击败对手，同时躲避 NPC 的拳头",
  clue: "NPC 每 10 秒挥拳一次；每 1.5 分钟需到集合圈报到，否则扣 1 滴血",
  hudClue: "NPC 每 10 秒挥拳 · 1.5 分钟集合 · 双方各 5 滴血",
  targetDesc: "对手",
  difficulty: 3,
  success: "你击败了对手，图书馆归于“平静”。",
  failure: "你被击败了",
  lighting: "library",
  duelMode: true,
};
