export const canvas = document.querySelector("#gameCanvas");

export const ui = {
  hud: document.querySelector("#hud"),
  sceneName: document.querySelector("#sceneName"),
  missionText: document.querySelector("#missionText"),
  mechanicHint: document.querySelector("#mechanicHint"),
  attemptChip: document.querySelector(".status-chip.danger"),
  timerText: document.querySelector("#timerText"),
  attemptText: document.querySelector("#attemptText"),
  clueBar: document.querySelector("#clueBar"),
  levelSelectModal: document.querySelector("#levelSelectModal"),
  levelSelectPanel: document.querySelector("#levelSelectPanel"),
  levelCards: document.querySelector("#levelCards"),
  extraLevelCards: document.querySelector("#extraLevelCards"),
  lifeTimeline: document.querySelector("#lifeTimeline"),
  taskModal: document.querySelector("#taskModal"),
  taskEmoji: document.querySelector("#taskEmoji"),
  taskTitle: document.querySelector("#taskTitle"),
  taskCopy: document.querySelector("#taskCopy"),
  taskClue: document.querySelector("#taskClue"),
  taskTime: document.querySelector("#taskTime"),
  taskAttempts: document.querySelector("#taskAttempts"),
  taskAttemptsChip: document.querySelector("#taskAttempts")?.parentElement,
  taskNpcCount: document.querySelector("#taskNpcCount"),
  npcCountInput: document.querySelector("#npcCountInput"),
  npcCountUp: document.querySelector(".match-settings-arrow.up"),
  npcCountDown: document.querySelector(".match-settings-arrow.down"),
  targetPreviewCanvas: document.querySelector("#targetPreviewCanvas"),
  targetLabel: document.querySelector("#targetLabel"),
  attackIcon: document.querySelector("#attackButton span"),
  startButton: document.querySelector("#startButton"),
  resultModal: document.querySelector("#resultModal"),
  resultRating: document.querySelector("#resultRating"),
  resultTitle: document.querySelector("#resultTitle"),
  resultCopy: document.querySelector("#resultCopy"),
  statTime: document.querySelector("#statTime"),
  statAttempts: document.querySelector("#statAttempts"),
  statAttemptsLabel: document.querySelector("#statAttemptsLabel"),
  damageFlash: document.querySelector("#damageFlash"),
  retryButton: document.querySelector("#retryButton"),
  backToSelectButton: document.querySelector("#backToSelectButton"),
  pauseButton: document.querySelector("#pauseButton"),
  pauseModal: document.querySelector("#pauseModal"),
  resumeButton: document.querySelector("#resumeButton"),
  backFromPauseButton: document.querySelector("#backFromPauseButton"),
  backFromTaskButton: document.querySelector("#backFromTaskButton"),
  gameLogo: document.querySelector("#gameLogo"),
  soloModeStack: document.querySelector("#soloModeStack"),
  attemptLabel: document.querySelector("#attemptLabel"),
  joystick: document.querySelector("#joystick"),
  joystickKnob: document.querySelector("#joystickKnob"),
  attackButton: document.querySelector("#attackButton"),
  cooldownOverlay: document.querySelector("#cooldownOverlay"),
};
